version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: petshop-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default

  redis:
    image:
      redis:7.0
    container_name: petshop-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - default

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petshop-backend
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    networks:
      - default

volumes:
  db_data: