
version: '3.8'

services:
  mysql:
    image: docker.io/library/mysql:8.0
    container_name: petshop-mysql
    environment:
      MYSQL_DATABASE: petshop
      MYSQL_ROOT_PASSWORD: petshop123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: docker.io/library/redis:7
    container_name: petshop-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  adminer:
    image: docker.io/library/adminer:latest
    container_name: petshop-adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  mysql-data:
