spring:
  cache:
    type: redis

  datasource:
    url: jdbc:mysql://db:3306/petshop  # 可改為 Railway/Render 對應資料庫
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: redis
    port: 6379

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      disable-swagger-default-url: true

server:
  port: 8080
